version: '3.1'

services:

  mysql:
    container_name: db_1day_mysql
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: treasure
      MYSQL_USER: treasure
      MYSQL_PASSWORD: treasure
      LANG: ja_JP.UTF-8
      TZ: "Asia/Tokyo"

  app:
    image: dkkoma/sql-migrate-bin:latest
    volumes:
      - ./db:/app
    working_dir: /app
    links:
      - mysql
      - mysql:database
